"""
This type stub file was generated by pyright.
"""

class ProgressLog:
    """Class to store the improvement of lower
    and upper bounds over time during the search.
    Results stored here are useful to analyze the
    performance of a given formulation/parameter setting
    for solving a instance. To be able to automatically
    generate summarized experimental results, fill the
    :attr:`~mip.ProgressLog.instance` and
    :attr:`~mip.ProgressLog.settings` of this object with the instance
    name and formulation/parameter setting details, respectively.

    Attributes:

        log(List[Tuple[float, Tuple[float, float]]]): List of tuples in the format
            :math:`(time, (lb, ub))`, where :math:`time` is the processing time
            in seconds and :math:`lb` and :math:`ub` are the lower and upper bounds,
            respectively

        instance(str): instance name

        settings(str): identification of the formulation/parameter
            settings used in the optimization (whatever is relevant to
            identify a given computational experiment)
    """
    def __init__(self) -> None:
        ...
    
    def write(self, file_name: str = ...): # -> None:
        """Saves the progress log. If no extension is informed,
        the :code:`.plog` extension will be used. If only a directory is
        informed then the name will be built considering the
        :attr:`~mip.ProgressLog.instance` and
        :attr:`~mip.ProgressLog.settings` attributes"""
        ...
    
    def read(self, file_name: str): # -> None:
        """Reads a progress log stored in a file"""
        ...
    


