"""
This type stub file was generated by pyright.
"""

import numbers
import mip
from . import Column, ConflictGraph, Constr, ConstrsGenerator, LinExpr, LinExprTensor, ProgressLog, Solver, Var
from .constants import ConstraintPriority
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple, Union

if TYPE_CHECKING:
    from collections.abc import Iterable

logger = ...
class Model:
    """Mixed Integer Programming Model

    This is the main class, providing methods for building, optimizing,
    querying optimization results and re-optimizing Mixed-Integer Programming
    Models.

    To check how models are created please see the
    :ref:`examples <chapExamples>` included.

    Attributes:
        vars(VarList): list of problem variables (:class:`~Var`)
        constrs(ConstrList): list of constraints (:class:`~Constr`)

    Examples:
        >>> from mip import Model, MAXIMIZE, CBC, INTEGER, OptimizationStatus
        >>> model = Model(sense=MAXIMIZE, solver_name=CBC)
        >>> x = model.add_var(name='x', var_type=INTEGER, lb=0, ub=10)
        >>> y = model.add_var(name='y', var_type=INTEGER, lb=0, ub=10)
        >>> model += x + y <= 10
        >>> model.objective = x + y
        >>> status = model.optimize(max_seconds=2)
        >>> status == OptimizationStatus.OPTIMAL
        True
    """
    def __init__(self: Model, name: str = ..., sense: str = ..., solver_name: str = ..., solver: Optional[Solver] = ...) -> None:
        """Model constructor

        Creates a Mixed-Integer Linear Programming Model. The default model
        optimization direction is Minimization. To store and optimize the model
        the MIP package automatically searches and connects in runtime to the
        dynamic library of some MIP solver installed on your computer, nowadays
        gurobi and cbc are supported. This solver is automatically selected,
        but you can force the selection of a specific solver with the parameter
        solver_name.

        Args:
            name (str): model name
            sense (str): mip.MINIMIZATION ("MIN") or mip.MAXIMIZATION ("MAX")
            solver_name(str): gurobi or cbc, searches for which
                solver is available if not informed
            solver(Solver): a (:class:`~Solver`) object; note that
                if this argument is provided, solver_name will be ignored
        """
        ...
    
    def __del__(self: Model) -> None:
        ...
    
    def __iadd__(self: Model, other) -> Model:
        ...
    
    def add_var(self: Model, name: str = ..., lb: numbers.Real = ..., ub: numbers.Real = ..., obj: numbers.Real = ..., var_type: str = ..., column: Column = ...) -> Var:
        """Creates a new variable in the model, returning its reference

        Args:
            name (str): variable name (optional)
            lb (numbers.Real): variable lower bound, default 0.0
            ub (numbers.Real): variable upper bound, default infinity
            obj (numbers.Real): coefficient of this variable in the objective
              function, default 0
            var_type (str): CONTINUOUS ("C"), BINARY ("B") or INTEGER ("I")
            column (Column): constraints where this variable will appear,
                necessary only when constraints are already created in
                the model and a new variable will be created.

        Examples:

            To add a variable :code:`x` which is continuous and greater or
            equal to zero to model :code:`m`::

                x = m.add_var()

            The following code adds a vector of binary variables
            :code:`x[0], ..., x[n-1]` to the model :code:`m`::

                x = [m.add_var(var_type=BINARY) for i in range(n)]

        :rtype: Var
        """
        ...
    
    def add_var_tensor(self: Model, shape: Tuple[int, ...], name: str, **kwargs) -> LinExprTensor:
        """Creates new variables in the model, arranging them in a numpy
        tensor and returning its reference

        Args:
            shape (Tuple[int, ...]): shape of the numpy tensor
            name (str): variable name
            **kwargs: all other named arguments will be used as
              :meth:`~mip.Model.add_var` arguments

        Examples:

            To add a tensor of variables :code:`x` with shape (3, 5) and which
            is continuous in any variable and have all values greater or equal
            to zero to model :code:`m`::

                x = m.add_var_tensor((3, 5), "x")

        :rtype: LinExprTensor
        """
        ...
    
    def add_constr(self: Model, lin_expr: LinExpr, name: str = ..., priority: ConstraintPriority = ...) -> Constr:
        r"""Creates a new constraint (row).

        Adds a new constraint to the model, returning its reference.

        Args:
            lin_expr(LinExpr): linear expression
            name(str): optional constraint name, used when saving model to
              lp or mps files
            priority(ConstraintPriority): optional constraint
              priority

        Examples:

        The following code adds the constraint :math:`x_1 + x_2 \leq 1`
        (x1 and x2 should be created first using
        :meth:`~mip.Model.add_var`)::

            m += x1 + x2 <= 1

        Which is equivalent to::

            m.add_constr( x1 + x2 <= 1 )

        Summation expressions can be used also, to add the constraint \
        :math:`\displaystyle \sum_{i=0}^{n-1} x_i = y` and name this \
        constraint :code:`cons1`::

            m += xsum(x[i] for i in range(n)) == y, "cons1"

        Which is equivalent to::

            m.add_constr( xsum(x[i] for i in range(n)) == y, "cons1" )

        :rtype: Constr
        """
        ...
    
    def add_lazy_constr(self: Model, expr: LinExpr) -> None:
        """Adds a lazy constraint

        A lazy constraint is a constraint that is only inserted
        into the model after the first integer solution that violates
        it is found. When lazy constraints are used a restricted
        pre-processing is executed since the complete model is not
        available at the beginning. If the number of lazy constraints
        is too large then they can be added during the search process
        by implementing a
        :class:`~ConstrsGenerator` and setting the
        property :attr:`~mip.Model.lazy_constrs_generator` of
        :class:`Model`.

        Args:
            expr(LinExpr): the linear constraint
        """
        ...
    
    def add_sos(self: Model, sos: List[Tuple[Var, numbers.Real]], sos_type: int) -> None:
        r"""Adds an Special Ordered Set (SOS) to the model

        An explanation on Special Ordered Sets is provided :ref:`here <chapSOS>`.


        Args:
            sos(List[Tuple[Var, numbers.Real]]):
                list including variables (not necessarily binary) and
                respective weights in the model
            sos_type(int):
                1 for Type 1 SOS, where at most one of the binary
                variables can be set to one and 2 for Type 2 SOS, where at
                most two variables from the list may be selected. In type
                2 SOS the two selected variables will be consecutive in
                the list.
        """
        ...
    
    def clear(self: Model) -> None:
        """Clears the model

        All variables, constraints and parameters will be reset. In addition,
        a new solver instance will be instantiated to implement the
        formulation.
        """
        ...
    
    def copy(self: Model, solver_name: str = ...) -> Model:
        """Creates a copy of the current model

        Args:
            solver_name(str): solver name (optional)

        :rtype: Model

        Returns:
            clone of current model
        """
        ...
    
    def constr_by_name(self: Model, name: str) -> Optional[Constr]:
        """Queries a constraint by its name

        Args:
            name(str): constraint name

        :rtype: Optional[Constr]

        Returns:
            constraint or None if not found
        """
        ...
    
    def var_by_name(self: Model, name: str) -> Optional[Var]:
        """Searchers a variable by its name

        :rtype: Optional[Var]

        Returns:
            Variable or None if not found
        """
        ...
    
    def clique_merge(self, constrs: Optional[List[Constr]] = ...) -> None:
        r"""This procedure searches for constraints with conflicting variables
        and attempts to group these constraints in larger constraints with all
        conflicts merged.

        For example, if your model has the following constraints:

        .. math::

            x_1 + x_2   \leq 1

            x_2 + x_3   \leq 1

            x_1 + x_3   \leq 1

        Then they can all be removed and replaced by the stronger inequality:

        .. math::

            x_1 + x_2 + x_3 \leq 1

        Args:
            constrs (Optional[List[Constr]]): constraints that should be checked for
              merging. All constraints will be checked if :code:`constrs` is None.

        """
        ...
    
    def generate_cuts(self: Model, cut_types: Optional[List[mip.CutType]] = ..., depth: int = ..., npass: int = ..., max_cuts: int = ..., min_viol: float = ...) -> mip.CutPool:
        """Tries to generate cutting planes for the current fractional
        solution. To optimize only the linear programming relaxation and not
        discard integrality information from variables you must call first
        :code:`model.optimize(relax=True)`.

        This method only works with the CBC mip solver, as Gurobi does not
        supports calling only cut generators.

        Args:
            cut_types (List[CutType]): types of cuts that can be generated, if
                an empty list is specified then all available cut generators
                will be called.
            depth: depth of the search tree, when informed the cut generator
                may decide to generate more/less cuts depending on the depth.
            max_cuts(int): cut separation will stop when at least max_cuts
                violated cuts were found.
            min_viol(float): cuts which are not violated by at least min_viol
                will be discarded.


        :rtype: mip.CutPool
        """
        ...
    
    @property
    def conflict_graph(self: Model) -> ConflictGraph:
        """: Returns the :class:`~mip.ConflictGraph` of a MIP model.

        :rtype: mip.ConflictGraph
        """
        ...
    
    def optimize(self: Model, max_seconds: numbers.Real = ..., max_nodes: int = ..., max_solutions: int = ..., max_seconds_same_incumbent: numbers.Real = ..., max_nodes_same_incumbent: int = ..., relax: bool = ...) -> mip.OptimizationStatus:
        """Optimizes current model

        Optimizes current model, optionally specifying processing limits.

        To optimize model :code:`m` within a processing time limit of
        300 seconds::

            m.optimize(max_seconds=300)

        Args:
            max_seconds (numbers.Real): Maximum runtime in seconds (default: inf)
            max_nodes (int): Maximum number of nodes (default: inf)
            max_solutions (int): Maximum number of solutions (default: inf)
            max_seconds_same_incumbent (numbers.Real): Maximum time in seconds
                that the search can go on if a feasible solution is available
                and it is not being improved
            max_nodes_same_incumbent (int): Maximum number of nodes
                that the search can go on if a feasible solution is available
                and it is not being improved
            relax (bool): if true only the linear programming relaxation will
                be solved, i.e. integrality constraints will be temporarily
                discarded.

        Returns:
            optimization status, which can be OPTIMAL(0), ERROR(-1),
            INFEASIBLE(1), UNBOUNDED(2). When optimizing problems
            with integer variables some additional cases may happen,
            FEASIBLE(3) for the case when a feasible solution was found
            but optimality was not proved, INT_INFEASIBLE(4) for the case
            when the lp relaxation is feasible but no feasible integer
            solution exists and NO_SOLUTION_FOUND(5) for the case when
            an integer solution was not found in the optimization.

        :rtype: mip.OptimizationStatus

        """
        ...
    
    def read(self: Model, path: str) -> None:
        """Reads a MIP model or an initial feasible solution.

           One of  the following file name extensions should be used
           to define the contents of what will be loaded:

           :code:`.lp`
             mip model stored in the
             `LP file format <https://www.ibm.com/support/knowledgecenter/SSSA5P_12.9.0/ilog.odms.cplex.help/CPLEX/GettingStarted/topics/tutorials/InteractiveOptimizer/usingLPformat.html>`_

           :code:`.mps`
             mip model stored in the
             `MPS file format <https://en.wikipedia.org/wiki/MPS_(format)>`_

           :code:`.sol`
             initial integer feasible solution

           :code:`.bas`
             `optimal basis <http://lpsolve.sourceforge.net/5.5/bas-format.htm>`_ for the linear programming relaxation.

        Note: if a new problem is readed, all variables, constraints
        and parameters from the current model will be cleared.

        Args:
            path(str): file name
        """
        ...
    
    def relax(self: Model) -> None:
        """Relax integrality constraints of variables

        Changes the type of all integer and binary variables to
        continuous. Bounds are preserved.
        """
        ...
    
    def write(self: Model, file_path: str) -> None:
        """Saves a MIP model or an initial feasible solution.

           One of  the following file name extensions should be used
           to define the contents of what will be saved:

           :code:`.lp`
             mip model stored in the
             `LP file format <https://www.ibm.com/support/knowledgecenter/SSSA5P_12.9.0/ilog.odms.cplex.help/CPLEX/GettingStarted/topics/tutorials/InteractiveOptimizer/usingLPformat.html>`_

           :code:`.mps`
             mip model stored in the
             `MPS file format <https://en.wikipedia.org/wiki/MPS_(format)>`_

           :code:`.sol`
             initial feasible solution

           :code:`.bas`
             `optimal basis <http://lpsolve.sourceforge.net/5.5/bas-format.htm>`_ for the linear programming relaxation.

        Args:
            file_path(str): file name
        """
        ...
    
    @property
    def objective_bound(self: Model) -> Optional[numbers.Real]:
        """:A valid estimate computed for the optimal solution cost, lower
        bound in the case of minimization, equals to
        :attr:`~mip.Model.objective_value` if the optimal solution was found.
        """
        ...
    
    @property
    def name(self: Model) -> str:
        """:The problem (instance) name.

        This name should be used to identify the instance that this model
        refers, e.g.: productionPlanningMay19. This name is stored when
        saving (:meth:`~mip.Model.write`) the model in :code:`.LP`
        or :code:`.MPS` file formats.
        """
        ...
    
    @name.setter
    def name(self: Model, name: str) -> None:
        ...
    
    @property
    def objective(self: Model) -> LinExpr:
        """The objective function of the problem as a linear expression.

        Examples:

            The following code adds all :code:`x` variables :code:`x[0],
            ..., x[n-1]`, to the objective function of model :code:`m`
            with the same cost :code:`w`::

                m.objective = xsum(w*x[i] for i in range(n))

            A simpler way to define the objective function is the use of the
            model operator += ::

                m += xsum(w*x[i] for i in range(n))

            Note that the only difference of adding a constraint is the lack of
            a sense and a rhs.

            :rtype: LinExpr
        """
        ...
    
    @objective.setter
    def objective(self: Model, objective: Union[numbers.Real, Var, LinExpr, LinExprTensor]) -> None:
        ...
    
    @property
    def verbose(self: Model) -> int:
        """0 to disable solver messages printed on the screen, 1 to enable"""
        ...
    
    @verbose.setter
    def verbose(self: Model, verbose: int) -> None:
        ...
    
    @property
    def lp_method(self: Model) -> mip.LP_Method:
        """Which  method should be used to solve the linear programming
        problem. If the problem has integer variables that this affects only
        the solution of the first linear programming relaxation.

        :rtype: mip.LP_Method
        """
        ...
    
    @lp_method.setter
    def lp_method(self: Model, lpm: mip.LP_Method) -> None:
        ...
    
    @property
    def threads(self: Model) -> int:
        r"""number of threads to be used when solving the problem.
        0 uses solver default configuration, -1 uses the number of available
        processing cores and :math:`\geq 1` uses the specified number of
        threads. An increased number of threads may improve the solution
        time but also increases the memory consumption."""
        ...
    
    @threads.setter
    def threads(self: Model, threads: int) -> None:
        ...
    
    @property
    def sense(self: Model) -> str:
        """The optimization sense

        Returns:
            the objective function sense, MINIMIZE (default) or (MAXIMIZE)
        """
        ...
    
    @sense.setter
    def sense(self: Model, sense: str) -> None:
        ...
    
    @property
    def objective_const(self: Model) -> float:
        """Returns the constant part of the objective function"""
        ...
    
    @objective_const.setter
    def objective_const(self: Model, objective_const: float) -> None:
        ...
    
    @property
    def objective_value(self: Model) -> Optional[numbers.Real]:
        """Objective function value of the solution found or None
        if model was not optimized
        """
        ...
    
    @property
    def gap(self: Model) -> float:
        r"""
        The optimality gap considering the cost of the best solution found
        (:attr:`~mip.Model.objective_value`)
        :math:`b` and the best objective bound :math:`l`
        (:attr:`~mip.Model.objective_bound`) :math:`g` is
        computed as: :math:`g=\\frac{|b-l|}{|b|}`.
        If no solution was found or if :math:`b=0` then :math:`g=\infty`.
        If the optimal solution was found then :math:`g=0`.
        """
        ...
    
    @property
    def search_progress_log(self: Model) -> ProgressLog:
        """:Log of bound improvements in the search.  The output of MIP
        solvers is a sequence of improving incumbent solutions (primal bound)
        and estimates for the optimal cost (dual bound). When the costs of
        these two bounds match the search is concluded. In truncated searches,
        the most common situation for hard problems, at the end of the search
        there is a :attr:`~mip.Model.gap` between these bounds. This property
        stores the detailed events of improving these bounds during the search
        process. Analyzing the evolution of these bounds you can see if you
        need to improve your solver w.r.t. the production of feasible
        solutions, by including an heuristic to produce a better initial
        feasible solution, for example, or improve the formulation with cutting
        planes, for example, to produce better dual bounds. To enable storing
        the :attr:`~mip.Model.search_progress_log` set
        :attr:`~mip.Model.store_search_progress_log` to True.

        :rtype: ProgressLog
        """
        ...
    
    @property
    def store_search_progress_log(self: Model) -> bool:
        """
        Wether :attr:`~mip.Model.search_progress_log` will be stored
        or not when optimizing. Default False. Activate it if you want to
        analyze bound improvements over time."""
        ...
    
    @store_search_progress_log.setter
    def store_search_progress_log(self: Model, store: bool) -> None:
        ...
    
    @property
    def num_solutions(self: Model) -> int:
        """Number of solutions found during the MIP search

        Returns:
            number of solutions stored in the solution pool

        """
        ...
    
    @property
    def objective_values(self: Model) -> List[numbers.Real]:
        """List of costs of all solutions in the solution pool

        Returns:
            costs of all solutions stored in the solution pool
            as an array from 0 (the best solution) to
            :attr:`~mip.Model.num_solutions`-1.
        """
        ...
    
    @property
    def cuts_generator(self: Model) -> Optional[ConstrsGenerator]:
        """A cuts generator is an :class:`~ConstrsGenerator`
        object that receives a fractional solution and tries to generate one or
        more constraints (cuts) to remove it. The cuts generator is called in
        every node of the branch-and-cut tree where a solution that violates
        the integrality constraint of one or more variables is found.

        :rtype: Optional[ConstrsGenerator]
        """
        ...
    
    @cuts_generator.setter
    def cuts_generator(self: Model, cuts_generator: Optional[ConstrsGenerator]) -> None:
        ...
    
    @property
    def lazy_constrs_generator(self: Model) -> Optional[ConstrsGenerator]:
        """A lazy constraints generator is an
        :class:`~ConstrsGenerator` object that receives
        an integer solution and checks its feasibility. If
        the solution is not feasible then one or more constraints can be
        generated to remove it. When a lazy constraints generator is informed
        it is assumed that the initial formulation is incomplete. Thus, a
        restricted pre-processing routine may be applied. If the initial
        formulation is incomplete, it may be interesting to use the same
        :class:`~ConstrsGenerator` to generate cuts *and* lazy
        constraints. The use of *only* lazy constraints may be useful then
        integer solutions rarely violate these constraints.

        :rtype: Optional[ConstrsGenerator]
        """
        ...
    
    @lazy_constrs_generator.setter
    def lazy_constrs_generator(self: Model, lazy_constrs_generator: Optional[ConstrsGenerator]) -> None:
        ...
    
    @property
    def emphasis(self: Model) -> mip.SearchEmphasis:
        """defines the main objective of the search, if set to 1 (FEASIBILITY)
        then the search process will focus on try to find quickly feasible
        solutions and improving them; if set to 2 (OPTIMALITY) then the
        search process will try to find a provable optimal solution,
        procedures to further improve the lower bounds will be activated in
        this setting, this may increase the time to produce the first
        feasible solutions but will probably pay off in longer runs;
        the default option if 0, where a balance between optimality and
        feasibility is sought.

        :rtype: mip.SearchEmphasis

        """
        ...
    
    @emphasis.setter
    def emphasis(self: Model, emphasis: mip.SearchEmphasis) -> None:
        ...
    
    @property
    def preprocess(self: Model) -> int:
        """Enables/disables pre-processing. Pre-processing tries to improve
        your MIP formulation. -1 means automatic, 0 means off and 1
        means on."""
        ...
    
    @preprocess.setter
    def preprocess(self: Model, prep: int) -> None:
        ...
    
    @property
    def pump_passes(self: Model) -> int:
        """Number of passes of the Feasibility Pump [FGL05]_ heuristic.
        You may increase this value if you are not getting feasible
        solutions."""
        ...
    
    @pump_passes.setter
    def pump_passes(self: Model, passes: int) -> None:
        ...
    
    @property
    def cuts(self: Model) -> int:
        """Controls the generation of cutting planes, -1 means automatic, 0
        disables completely, 1 (default) generates cutting planes in a moderate
        way, 2 generates cutting planes aggressively and 3 generates even more
        cutting planes. Cutting planes usually improve the LP relaxation bound
        but also make the solution time of the LP relaxation larger, so the
        overall effect is hard to predict and experimenting different values
        for this parameter may be beneficial."""
        ...
    
    @cuts.setter
    def cuts(self: Model, gencuts: int) -> None:
        ...
    
    @property
    def cut_passes(self: Model) -> int:
        """Maximum number of rounds of cutting planes. You may set this
        parameter to low values if you see that a significant amount of
        time is being spent generating cuts without any improvement in
        the lower bound. -1 means automatic, values greater than zero
        specify the maximum number of rounds."""
        ...
    
    @cut_passes.setter
    def cut_passes(self: Model, cp: int) -> None:
        ...
    
    @property
    def clique(self: Model) -> int:
        """Controls the generation of clique cuts. -1 means automatic,
        0 disables it, 1 enables it and 2 enables more aggressive clique
        generation."""
        ...
    
    @clique.setter
    def clique(self: Model, clq: int) -> None:
        ...
    
    @property
    def start(self: Model) -> Optional[List[Tuple[Var, numbers.Real]]]:
        """Initial feasible solution

        Enters an initial feasible solution. Only the main binary/integer
        decision variables which appear with non-zero values in the initial
        feasible solution need to be informed. Auxiliary or continuous
        variables are automatically computed.

        :rtype: Optional[List[Tuple[Var, numbers.Real]]]
        """
        ...
    
    @start.setter
    def start(self: Model, start: Optional[List[Tuple[Var, numbers.Real]]]) -> None:
        ...
    
    def validate_mip_start(self: Model) -> None:
        """Validates solution entered in MIPStart

        If the solver engine printed messages indicating that the initial
        feasible solution that you entered in :attr:`~mip.Model.start` is not
        valid then you can call this method to help discovering which set of
        variables is causing infeasibility. The current version is quite
        simple: the model is relaxed and one variable entered in mipstart is
        fixed per iteration, indicating if the model still feasible or not.
        """
        ...
    
    @property
    def num_cols(self: Model) -> int:
        """number of columns (variables) in the model"""
        ...
    
    @property
    def num_int(self: Model) -> int:
        """number of integer variables in the model"""
        ...
    
    @property
    def num_rows(self: Model) -> int:
        """number of rows (constraints) in the model"""
        ...
    
    @property
    def num_nz(self: Model) -> int:
        """number of non-zeros in the constraint matrix"""
        ...
    
    @property
    def cutoff(self: Model) -> numbers.Real:
        """upper limit for the solution cost, solutions with cost > cutoff
        will be removed from the search space, a small cutoff value may
        significantly speedup the search, but if cutoff is set to a value too
        low the model will become infeasible"""
        ...
    
    @cutoff.setter
    def cutoff(self: Model, cutoff: float) -> None:
        ...
    
    @property
    def integer_tol(self: Model) -> float:
        """Maximum distance to the nearest integer for a variable to be
        considered with an integer value. Default value: 1e-6. Tightening this
        value can increase the numerical precision but also probably increase
        the running time. As floating point computations always involve some
        loss of precision, values too close to zero will likely render some
        models impossible to optimize."""
        ...
    
    @integer_tol.setter
    def integer_tol(self: Model, int_tol: float) -> None:
        ...
    
    @property
    def infeas_tol(self: Model) -> float:
        """Maximum allowed violation for constraints.

        Default value: 1e-6.  Tightening this value can increase the numerical
        precision but also probably increase the running time. As floating
        point computations always involve some loss of precision, values too
        close to zero will likely render some models impossible to optimize."""
        ...
    
    @infeas_tol.setter
    def infeas_tol(self: Model, inf_tol: float) -> None:
        ...
    
    @property
    def opt_tol(self: Model) -> float:
        """Maximum reduced cost value for a solution of the LP relaxation to be
        considered optimal. Default value: 1e-6.  Tightening this value can
        increase the numerical precision but also probably increase the running
        time. As floating point computations always involve some loss of
        precision, values too close to zero will likely render some models
        impossible to optimize."""
        ...
    
    @opt_tol.setter
    def opt_tol(self: Model, tol: float) -> None:
        ...
    
    @property
    def max_mip_gap_abs(self: Model) -> float:
        """Tolerance for the quality of the optimal solution, if a solution
        with cost :math:`c` and a lower bound :math:`l` are available and
        :math:`c-l<` :code:`mip_gap_abs`, the search will be concluded, see
        :attr:`~mip.Model.max_mip_gap` to determine a percentage value.
        Default value: 1e-10."""
        ...
    
    @max_mip_gap_abs.setter
    def max_mip_gap_abs(self: Model, max_mip_gap_abs: float) -> None:
        ...
    
    @property
    def max_mip_gap(self: Model) -> float:
        """value indicating the tolerance for the maximum percentage deviation
        from the optimal solution cost, if a solution with cost :math:`c` and
        a lower bound :math:`l` are available and
        :math:`(c-l)/l <` :code:`max_mip_gap` the search will be concluded.
        Default value: 1e-4."""
        ...
    
    @max_mip_gap.setter
    def max_mip_gap(self: Model, max_mip_gap: float) -> None:
        ...
    
    @property
    def max_seconds(self: Model) -> float:
        """time limit in seconds for search"""
        ...
    
    @max_seconds.setter
    def max_seconds(self: Model, max_seconds: float) -> None:
        ...
    
    @property
    def max_nodes(self: Model) -> int:
        """maximum number of nodes to be explored in the search tree"""
        ...
    
    @max_nodes.setter
    def max_nodes(self: Model, max_nodes: int) -> None:
        ...
    
    @property
    def max_solutions(self: Model) -> int:
        """solution limit, search will be stopped when :code:`max_solutions`
        were found"""
        ...
    
    @max_solutions.setter
    def max_solutions(self: Model, max_solutions: int) -> None:
        ...
    
    @property
    def seed(self: Model) -> int:
        """Random seed. Small changes in the first decisions while solving the LP
        relaxation and the MIP can have a large impact in the performance,
        as discussed in [Fisch14]_. This behaviour can be exploited with multiple
        independent runs with different random seeds."""
        ...
    
    @seed.setter
    def seed(self: Model, seed: int) -> None:
        ...
    
    @property
    def round_int_vars(self: Model) -> bool:
        """MIP solvers perform computations using *limited precision* arithmetic.
        Thus a variable with value 0 may appear in the solution as
        0.000000000001. Thus, comparing this var to zero would return false.
        The safest approach would be to use something like abs(v.x) < 1e-7.
        To simplify code the solution value of integer variables can be
        automatically rounded to the nearest integer and then, comparisons like
        v.x == 0 would work. Rounding is not always a good idea specially in
        models with numerical instability, since it can increase the
        infeasibilities."""
        ...
    
    @round_int_vars.setter
    def round_int_vars(self: Model, round_iv: bool) -> None:
        ...
    
    @property
    def sol_pool_size(self: Model) -> int:
        """Maximum number of solutions that will be stored during the search.
        To check how many solutions were found during the search use
        :meth:`~mip.Model.num_solutions`."""
        ...
    
    @sol_pool_size.setter
    def sol_pool_size(self: Model, sol_pool_size: int) -> None:
        ...
    
    @property
    def status(self: Model) -> mip.OptimizationStatus:
        """optimization status, which can be OPTIMAL(0), ERROR(-1),
        INFEASIBLE(1), UNBOUNDED(2). When optimizing problems
        with integer variables some additional cases may happen, FEASIBLE(3)
        for the case when a feasible solution was found but optimality was
        not proved, INT_INFEASIBLE(4) for the case when the lp relaxation is
        feasible but no feasible integer solution exists and
        NO_SOLUTION_FOUND(5) for the case when an integer solution was not
        found in the optimization.

        :rtype: mip.OptimizationStatus
        """
        ...
    
    def add_cut(self: Model, cut: LinExpr) -> None:
        """Adds a violated inequality (cutting plane) to the linear programming
        model. If called outside the cut callback performs exactly as
        :meth:`~mip.Model.add_constr`. When called inside the cut
        callback the cut is included in the solver's cut pool, which will later
        decide if this cut should be added or not to the model. Repeated cuts,
        or cuts which will probably be less effective, e.g. with a very small
        violation, can be discarded.

        Args:
            cut(LinExpr): violated inequality
        """
        ...
    
    def remove(self: Model, objects: Union[Var, Constr, List[Union[Var, Constr]]]) -> None:
        """removes variable(s) and/or constraint(s) from the model

        Args:
            objects (Union[Var, Constr, List[Union[Var, Constr]]]):
                can be a :class:`~Var`, a :class:`~Constr` or a list of these objects
        """
        ...
    
    def translate(self: Model, ref) -> Union[List[Any], Dict[Any, Any], Var]:
        """Translates references of variables/containers of variables
        from another model to this model. Can be used to translate
        references of variables in the original model to references
        of variables in the pre-processed model.

        :rtype: Union[List[Any], Dict[Any, Any], Var]
        """
        ...
    
    def check_optimization_results(self) -> None:
        """Checks the consistency of the optimization results, i.e., if the
        solution(s) produced by the MIP solver respect all constraints and
        variable values are within acceptable bounds and are integral when
        requested."""
        ...
    
    def reset(self) -> None:
        """Discards the current solution, putting the model to an unsolved state."""
        ...
    


def maximize(objective: Union[LinExpr, Var]) -> LinExpr:
    """
    Function that should be used to set the objective function to MAXIMIZE
    a given linear expression (passed as argument).

    Args:
        objective(Union[LinExpr, Var]): linear expression

    :rtype: LinExpr
    """
    ...

def minimize(objective: Union[LinExpr, Var]) -> LinExpr:
    """
    Function that should be used to set the objective function to MINIMIZE
    a given linear expression (passed as argument).

    Args:
        objective(Union[LinExpr, Var]): linear expression

    :rtype: LinExpr
    """
    ...

def xsum(terms: Iterable[Var | LinExpr | numbers.Real]) -> LinExpr:
    """
    Function that should be used to create a linear expression from a
    summation. While the python function sum() can also be used, this
    function is optimized version for quickly generating the linear
    expression.

    Args:
        terms: set (ideally a list) of terms to be summed

    :rtype: LinExpr
    """
    ...

def compute_features(model: Model) -> List[float]:
    """This function computes instance features for a MIP. Features are
    instance characteristics, such as number of columns, rows, matrix density,
    etc. These features can be used in machine learning algorithms to recommend
    parameter settings. To check names of features that are computed in this
    vector use :py:meth:`~mip.features`

    Arguments:
        model(Model): the MIP model were features will be extracted
    """
    ...

def features() -> List[str]:
    """This function returns the list of problem feature names that can be
    computed :py:meth:`~mip.compute_features`
    """
    ...

quicksum = ...
def save_mipstart(sol: List[Tuple[Var, numbers.Real]], file_name: str, obj=...) -> None:
    """Saves a solution in a MIPStart (MST) file."""
    ...

def load_mipstart(file_name: str) -> List[Tuple[str, numbers.Real]]:
    """Loads a MIPStart (MST) file."""
    ...

def read_custom_settings() -> None:
    ...

customCbcLib = ...
